### ISSUE TITLE
Golden Sun

### ISSUE THREAD

**Issue by grantgalitz** [grantgalitz/IodineGBA#27]
General instability.

**Comment by endrift** [comment]
I've seen the bug you get at the beginning when sliding out of the bed before. It's caused by a bug in one of the long multiplies. I forget which one.

**Comment by grantgalitz** [comment]
https://github.com/grantgalitz/IodineGBA/commit/0d873eab1d74a7f4811d91198c795480217962eb

Bug in the emulator was the Math.floor missing.

**Comment by grantgalitz** [comment]
Also you might want to check for precision loss with that stuff. Hopefully your precision is saved by proper exponent increments + decrements, but I played it safe and used double divide by 0x100000000 to shift right by 32.

**Comment by grantgalitz** [comment]
Adding math.floor for correct negative number rounding fixed some demo scene roms as well and a Lego racing game.
